#!/bin/sh

set -e

. $(dirname $0)/functions.sh

# Get the current address
ADDRESS=$(
    curl -s http://ipdetect.dnspark.com/ | \
    grep 'Current Address:' | \
    sed 's/Current Address: //'
)

CURRENT_ADDRESS=$(get_record_id A '' content)

if [ $ADDRESS = $CURRENT_ADDRESS ]
then
    echo "Address is current."
    exit 0
fi

RECORD_ID=$(get_record_id A '')

# Update the address
curl \
    -s \
    -H "PddToken: $TOKEN" \
    -d "domain=$DOMAIN&record_id=$RECORD_ID&content=$ADDRESS" \
    $BASE_URL/edit
