#!/bin/sh

set -e

. $(dirname $0)/functions.sh

# Get the current address
ADDRESS=$(curl -s https://ifconfig.me)

CURRENT_ADDRESS=$(get_record_ip A '')

if [ "$ADDRESS" = "$CURRENT_ADDRESS" ]
then
    echo "Address is current."
    exit 0
fi

RECORD_ID=$(get_record_id A '')

# Update the address
set_record_ip $RECORD_ID $ADDRESS
